name: Tests with reporter
on:
  push:
    branches: [ main, master ]

jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm i npm@latest
            - run: npm i
            - name: run test
              run: npm run cy:run
            - name: Create Report
              if: always()
              run: npm run allure:generate
            - name: Upload artifact allure-report
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: allure-report
                  path: ./allure-report
            - name: Deploy report
              uses: JamesIves/github-pages-deploy-action@3.1.0
              if: always()
              with:
                  BRANCH: master # The branch the action should deploy to.
                  FOLDER: allure-report # The folder the action should deploy.
                  TARGET_FOLDER: docs




# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Cypress install
#         uses: cypress-io/github-action@v4
#         with:
#           browser: chrome
#           runTests: false
#       - name: Cypress run
#         run: npm run cy:run
#       - name: Generate Allure report
#         if: always()
#         run: npm run allure:generate
#       - name: Upload Results
#         uses: actions/upload-artifact@v1
#         if: always()
#         with:
#           name: allure-results
#           path: ./allure-results 
#       - name: Publishing Allure artifact to Github Actions
#         uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: allure-report
#           path: ./allure-report
#       - name: Deploy report
#         uses: JamesIves/github-pages-deploy-action@4.1.3
#         if: always()
#         with:
#           branch: gh-pages 
#           folder: allure-report 